const List<Map<String, String>> JobData = [
  {
    "id": "1",
    "name": "Delivery",
    "price": "150",
    "time": "7-9 pm",
    "description": "Deliver various items such as food, groceries, or packages to specified locations within the given time frame.",
    "userId": "1",
  },
  {
    "id": "2",
    "name": "Babysit",
    "price": "100",
    "time": "7-9 pm",
    "description": "Take care of children in their home environment, ensuring their safety, feeding them, and engaging them in age-appropriate activities.",
    "userId": "2",
  },
  {
    "id": "3",
    "name": "Cook assistant",
    "price": "50",
    "time": "1-2 pm",
    "description": "Assist the head cook in meal preparation, including chopping vegetables, preparing ingredients, and cleaning kitchen utensils.",
    "userId": "3",
  },
  {
    "id": "4",
    "name": "Home Work assistant for grade five",
    "price": "70",
    "time": "8-9.30 pm",
    "description": "Provide academic support to a fifth-grade student with their homework, assignments, and comprehension of various subjects.",
    "userId": "4",
  },
  {
    "id": "5",
    "name": "Barista",
    "price": "300",
    "time": "10 am - 9 pm",
    "description": "Prepare and serve coffee, tea, and other beverages to customers in a café or coffee shop, while ensuring high-quality service and cleanliness.",
    "userId": "5",
  },
  {
    "id": "6",
    "name": "Delivery a gift",
    "price": "200",
    "description": "Deliver a specific gift item to the recipient's address within the given time frame.",
    "userId": "1",
  },
  {
    "id": "7",
    "name": "Delivery a gift",
    "price": "200",
    "description": "Deliver a specific gift item to the recipient's address within the given time frame.",
    "userId": "1",
  },
];
